nama = input("Nama kamu? : ")
umur = input("Umur kamu? : ")
sex = input("Jenis Kelamin? : ")
job = input("Pekerjaan kamu? : ")
print("Nama : " + nama)
print("umur : " + umur)
print("Kelamin : " + sex)
print("Pekerjaan : " + job)